services:
  backend:
    build:
      context: ..
      dockerfile: .docker/node/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      # SQLite soubor přežije restart kontejneru
      - db-data:/app/data
    restart: unless-stopped

  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - db-data:/data
    command: sqlite_web -x -H 0.0.0.0 /data/panobed.db
    restart: unless-stopped

volumes:
  db-data:
